name = "design-gallery-backend"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Environment variables (non-sensitive only)
[vars]
ENVIRONMENT = "development"
# JWT_SECRET is stored as a Cloudflare secret - not here!
CORS_ORIGINS = "*"
MAX_FILE_SIZE = "10485760"
DEFAULT_PAGE_SIZE = "20"
MAX_PAGE_SIZE = "100"
R2_PUBLIC_URL = "https://pub-0b3de96b3a72833e38311290e9acfc3a.r2.dev"
CLOUDFLARE_ACCOUNT_ID = "0b3de96b3a72833e38311290e9acfc3a"

# D1 Database binding (REMOTE - no local)
[[d1_databases]]
binding = "DB"
database_name = "design-gallery-db"
database_id = "d6b6a330-ee0e-4ffb-9382-51af55485da4"

# R2 Storage binding (REMOTE - no local)
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "designs"

# KV namespace removed - not required for basic functionality
# Rate limiting will use in-memory fallback

# Production environment configuration
[env.production]
# JWT_SECRET for production is stored as a Cloudflare secret

[env.production.vars]
ENVIRONMENT = "production"
CORS_ORIGINS = "https://yourdomain.com"
MAX_FILE_SIZE = "10485760"
DEFAULT_PAGE_SIZE = "20"
MAX_PAGE_SIZE = "100"
R2_PUBLIC_URL = "https://your-production-r2-domain.com"
CLOUDFLARE_ACCOUNT_ID = "0b3de96b3a72833e38311290e9acfc3a"

[[env.production.d1_databases]]
binding = "DB"
database_name = "design-gallery-db-prod"
database_id = "your-production-d1-database-id"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "design-gallery-uploads-prod"

# KV namespace removed - not required for basic functionality

# Preview environment (for testing before production)
[env.preview]
# JWT_SECRET for preview is stored as a Cloudflare secret

[env.preview.vars]
ENVIRONMENT = "preview"
CORS_ORIGINS = "*"
MAX_FILE_SIZE = "10485760"
DEFAULT_PAGE_SIZE = "20"
MAX_PAGE_SIZE = "100"
R2_PUBLIC_URL = "https://pub-0b3de96b3a72833e38311290e9acfc3a.r2.dev"
CLOUDFLARE_ACCOUNT_ID = "0b3de96b3a72833e38311290e9acfc3a"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "design-gallery-db-preview"
database_id = "your-preview-d1-database-id"

[[env.preview.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "design-gallery-uploads-preview"

# KV namespace removed - not required for basic functionality 